declare const _default: {
    black: string;
    blackRGB: string;
    borderColor: string;
    danger: string;
    dangerRGB: string;
    darkGrey: string;
    darkGreyRGB: string;
    disabled: string;
    disabledRGB: string;
    info: string;
    infoRGB: string;
    lightGrey: string;
    lightGreyRGB: string;
    primary: string;
    primaryRGB: string;
    secondary: string;
    secondaryRGB: string;
    success: string;
    successRGB: string;
    warning: string;
    warningRGB: string;
    white: string;
    whiteRGB: string;
};
export default _default;
